name = "ssh-executor-worker"
main = "src/index.ts"
compatibility_date = "2024-12-01"
account_id = "9a877cdba770217082a2f914427df505"

[vars]
SSH_HOST = "178.62.246.169"
SSH_USER = "root"
COOLIFY_URL = "https://coolify.ofshore.dev"
